#!/bin/bash
# ──────────────────────────────────────────────────────────────────
# EO Strata Demo Simulator - One-Time Setup
# ──────────────────────────────────────────────────────────────────
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║   EO Strata Demo Simulator - Setup              ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

# ─── Create virtual environment ──────────────────────────────────
if [ ! -d "venv" ]; then
    echo "→ Creating Python virtual environment..."
    python3 -m venv venv
    echo "  ✓ Virtual environment created"
else
    echo "  ✓ Virtual environment already exists"
fi

# ─── Activate and install dependencies ───────────────────────────
echo "→ Installing dependencies..."
source venv/bin/activate
pip install --quiet --upgrade pip
pip install --quiet -r requirements.txt
echo "  ✓ Dependencies installed"

# ─── Configure credentials ───────────────────────────────────────
echo ""

if [ -f ".env" ]; then
    echo "  ✓ .env file already exists"
    echo ""
    read -p "  Overwrite with new credentials? (y/N): " OVERWRITE
    if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
        echo ""
        echo "  Keeping existing .env. Setup complete!"
        echo "  Run the demo:  ./run.sh"
        echo ""
        exit 0
    fi
    echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Credential Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  You'll need a few values to run the demo."
echo "  Each will be stored in a local .env file."
echo ""

# ── BigPanda Region ──────────────────────────────────────────────
echo "  1) BigPanda Region"
echo "     US = api.bigpanda.io  (default)"
echo "     EU = eu-api.bigpanda.io"
echo ""
read -p "     Select region [US/EU] (default: US): " BP_REGION
BP_REGION="${BP_REGION:-US}"
BP_REGION=$(echo "$BP_REGION" | tr '[:lower:]' '[:upper:]')
if [[ "$BP_REGION" != "US" && "$BP_REGION" != "EU" ]]; then
    echo "     Invalid region '$BP_REGION', defaulting to US"
    BP_REGION="US"
fi
echo "     → Region set to: $BP_REGION"
echo ""

# ── BigPanda Org Access Token ────────────────────────────────────
echo "  2) BigPanda Org Access Token"
echo "     Where to find it: BigPanda → Integrations → Select an Integration → Setup Instructions"
echo ""
read -p "     Paste your Org Access Token: " BP_TOKEN
echo ""

# ── BigPanda OIM App Key ─────────────────────────────────────────
echo "  3) BigPanda OIM Integration App Key"
echo "     Where to find it: BigPanda → Integrations → Open Integration Manager"
echo "                        → Select your integration → App Key"
echo ""
read -p "     Paste your OIM App Key: " BP_APP_KEY
echo ""

# ── BigPanda Org Name ────────────────────────────────────────────
echo "  4) BigPanda Org Name"
echo "     The name of the BigPanda org this demo targets (for display purposes)."
echo "     Leave blank to auto-detect from the Org Token on startup."
echo ""
read -p "     Org Name (or press Enter to skip): " BP_ORG_NAME
echo ""

# ── OpenAI API Key ───────────────────────────────────────────────
echo "  5) OpenAI API Key"
echo "     Where to find it: https://platform.openai.com/api-keys"
echo ""
read -p "     Paste your OpenAI API Key: " OPENAI_KEY
echo ""

# ── Write .env file ──────────────────────────────────────────────
cat > .env << ENVEOF
# ──────────────────────────────────────────────────────────────────
# EO Strata Demo Simulator - Environment Configuration
# Generated by setup.sh on $(date '+%Y-%m-%d %H:%M:%S')
# ──────────────────────────────────────────────────────────────────

# BigPanda Region (US or EU — determines API endpoint base URLs)
BIGPANDA_REGION=${BP_REGION}

# BigPanda Org Access Token (Bearer token for API authentication)
BIGPANDA_ORG_ACCESS_TOKEN=${BP_TOKEN}

# BigPanda OIM Integration App Key (routes alerts to the correct integration)
BIGPANDA_APP_KEY=${BP_APP_KEY}

# BigPanda Org Name (for display; auto-detected from token if blank)
BIGPANDA_ORG_NAME=${BP_ORG_NAME}

# OpenAI API Key (for generating realistic alert payloads)
OPENAI_API_KEY=${OPENAI_KEY}

# ──────────────────────────────────────────────────────────────────
# Optional Overrides (defaults are fine for most use cases)
# ──────────────────────────────────────────────────────────────────

# Override the OIM alerts endpoint (resolved automatically from BIGPANDA_REGION)
# BIGPANDA_ALERTS_URL=https://integrations.bigpanda.io/oim/api/alerts

# OpenAI model for alert generation (default: gpt-5-mini)
# OPENAI_MODEL=gpt-5-mini
ENVEOF

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✓ .env file created with your credentials"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Setup complete! Run the demo:"
echo "  ./run.sh"
echo ""
echo "Optional: Configure the OIM integration first:"
echo "  ./run.sh --setup-oim"
echo ""
